// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmyFF2PhM0yGwuwmgYyBW4gzcOW1gQVSY',
    appId: '1:733935937931:web:e52a7cea3568ce6971e78e',
    messagingSenderId: '733935937931',
    projectId: 'plant-disease-1',
    authDomain: 'plant-disease-1.firebaseapp.com',
    storageBucket: 'plant-disease-1.firebasestorage.app',
    measurementId: 'G-ZCT2D60V9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd_KMMBFIYMZ6oTfjl4oBKDMzRgg2lr3o',
    appId: '1:733935937931:android:ccc63d11cebea65a71e78e',
    messagingSenderId: '733935937931',
    projectId: 'plant-disease-1',
    storageBucket: 'plant-disease-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMU7ulpTI_xMEI5CLIyrYH3i2ZJdSu0Cw',
    appId: '1:733935937931:ios:eb2a662d481b308571e78e',
    messagingSenderId: '733935937931',
    projectId: 'plant-disease-1',
    storageBucket: 'plant-disease-1.firebasestorage.app',
    iosBundleId: 'com.example.plantAplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMU7ulpTI_xMEI5CLIyrYH3i2ZJdSu0Cw',
    appId: '1:733935937931:ios:eb2a662d481b308571e78e',
    messagingSenderId: '733935937931',
    projectId: 'plant-disease-1',
    storageBucket: 'plant-disease-1.firebasestorage.app',
    iosBundleId: 'com.example.plantAplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmyFF2PhM0yGwuwmgYyBW4gzcOW1gQVSY',
    appId: '1:733935937931:web:98f4d57e79d370b971e78e',
    messagingSenderId: '733935937931',
    projectId: 'plant-disease-1',
    authDomain: 'plant-disease-1.firebaseapp.com',
    storageBucket: 'plant-disease-1.firebasestorage.app',
    measurementId: 'G-WXBXWD9X19',
  );
}
